name: Build & Deploy Delivery
on:
  push:
    branches: ["main"]
    paths:
      - 'Backend/delivery_api/**'
      - captain-definition-delivery-api

  pull_request:
    branches: ["main"]
    paths:
      - 'Backend/delivery_api/**'
      - captain-definition-delivery-api
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@main

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            Backend/
            Backend/jwt-auth.lua
            captain-definition-delivery-api
          outPath: deploy.tar

      - name: Deploy DELIVERY-API
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.APP_NAME_DELIVERY_API }}"
          token: "${{ secrets.APP_TOKEN_DELIVERY_API }}"